<?php

	$ustrojbene_jedinice = array(
		1 => "ODSJEK ZA HRVATSKI JEZIK I KNJIŽEVNOST",
		2 => "ODSJEK ZA POVIJEST",
		3 => "ODSJEK ZA INFORMACIJSKE ZNANOSTI",
		4 => "ODSJEK ZA ENGLESKI JEZIK I KNJIŽEVNOST",
		5 => "ODSJEK ZA NJEMAČKI JEZIK I KNJIŽEVNOST",
		6 => "ODSJEK ZA PEDAGOGIJU",
		7 => "ODSJEK ZA FILOZOFIJU",
		8 => "ODSJEK ZA PSIHOLOGIJU",
		9 => "KATEDRA ZA MAĐARSKI JEZIK I KNJIŽEVNOST",
		12 => "KATEDRA ZA SOCIOLOGIJU",
		13 => "POVIJEST UMJETNOSTI"
	);

?>